### ISSUE TITLE
off topic

### ISSUE THREAD

**Issue by cloudson** [joaovictor3g/simple-github-repo-list#3]
Hey João, eu perdi seu contato, não lembro por onde você me mandou seu repositório, mas to passando pra dizer que curti muito e vou mostrar ele num vídeo para inspirar outros inscritos do canal. Eu achei um ou dois erros no projeto, mas a ideia é que as pessoas peguem nesse problema e te ajudem a resolver, então se você ver o vídeo não resolva para dar chance para outras pessoas estudarem também 😉. 

Obs: fecha a issue quando ler isso.

**Comment by joaovictor3g** [comment]
Boa, valeu manow
